export const kinkOptions = [
  "swinging",
  "softswap",
  "polyamory",
  "bondage",
  "oralsex",
  "spanking",
  "hairpulling",
  "analsex",
  "blindfolds",
  "biting",
  "talkingdirty",
  "handcuffs",
  "lingerie",
  "discipline",
  "assplay",
  "collarandleadleash",
  "toys",
  "orgiesgroupsex",
  "candlewax",
  "breastnippleplay",
  "sexinpublic",
  "masturbation",
  "mutualmasturbation",
  "roleplay",
  "masterslave",
  "dildos",
  "vibrators",
  "eroticphotography",
  "pain",
  "highheels",
  "strap-ons",
  "humiliation",
  "whips",
  "exhibitionism",
  "rimming",
  "roughsex",
  "barebottomspanking",
  "nipples",
  "blowjobs",
  "breathplay",
  "voyeurism",
  "fisting",
  "sensorydeprivation",
  "gangbangs",
  "powerexchange",
  "makinghomemovies",
  "pantyhosestockings",
  "chains",
  "leather",
  "ageplay",
  "piercings",
  "watersports",
  "barehandedspanking",
  "facefucking",
  "cagingconfinement",
  "threesomes",
  "cunnilingus",
  "kissing",
  "deepthroating",
  "buttplugs",
  "intelligence",
  "latex",
  "orgasmcontrol",
  "cuddles",
  "multipleorgasms",
  "sugardaddysugarbaby",
  "chastitydevices",
  "domination",
  "chokingplay",
  "anal",
  "doublepenetration",
  "restraints",
  "sadism",
  "consensualnonconsentplay",
  "corsets",
  "tattoos",
  "masochism",
  "squirting",
  "fingering",
  "collars",
  "gaggingchokedbycock",
  "ballgags",
  "faceslapping",
  "footfeet",
  "masks",
  "ropebondagesuspension",
  "bdsm",
  "outdoorsex",
  "massages",
  "begging",
  "doctornurseplay",
  "crossdressing",
  "femaleejaculation",
  "obediencetraining",
  "orgasmdenial",
  "teasing",
  "cocksucking",
  "submission",
  "flogging",
  "cockandballtorture",
  "beltspanking",
  "daddygirl",
  "enemas",
  "costumesdressingup",
  "cockworship",
  "cuddling",
  "dating",
];

export const sexOptions = ["F", "M", "N", "MF", "FF", "MM", "NN", "FN", "MN"];

export const sexSingleOptions = ["F", "M", "I", "N"];

export const distanceOptions = ["5", "10", "20", "50"];

export const langOptions = ["en", "es", "fr", "de"];

export const sexualityOptions = ["he", "ho", "bi", "pa", "qu", "as"];

export const eventTypeOptions = ["public", "private"];
